## Indicator definitions
This document will provide details of all indicators discussed in the readme file.

* **TB Notification ALL**: This indicator calculates the total number of TB patients notified in a period of interest. This indicator is applicable to the following datasets
1. TB Notification 2018:- it sums up all clients reported in block 1 columns 2 to 4 (i.e Pulmonary Bacteriologically Confirmed, Pulmonary Clinically Diagnosed, Extra-pulmonary (bacteriologically confirmed or clinically diagnosed) accross all rows.
2. TB_Notification_New:- It sums up patients in all columns accross all rows in block 1.  
3. TB Case Registration Old:- It sums up patients in all columns accross all rows in block 1 excluding the sub-totals.

* **TB Notification New and Relapse**: This indicator calculates the number of TB patients notified in a period of interest who are either relapse or new. This indicator is applicable to the following datasets
1. TB Notification 2018:- it sums up all clients reported in block 1 columns 2 to 4 (i.e Pulmonary Bacteriologically Confirmed, Pulmonary Clinically Diagnosed, Extra-pulmonary (bacteriologically confirmed or clinically diagnosed) accross **New** and **Relapse** rows.
2. TB_Notification_New:- It sums up patients in **New** and **Relapse** columns accross all rows in block 1.  
3. TB Case Registration Old:- It sums up patients in **New** and **Relapse** columns accross all rows in block 1 excluding the sub-totals.
